# Generated by Django 6.1.1 on 2026-09-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('categoria', models.CharField(default='estandar', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
