# Generated by Django 6.1.1 on 2026-09-15 22:19

import datetime
import django.db.models.deletion
import encrypted_model_fields.fields
import gestion_servicios.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='color',
            field=models.CharField(blank=True, help_text='Color hexadecimal para diferenciarlo en el Calendario. Se asigna solo si se deja vacio', max_length=7),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 9, 15, 22, 19, 1, 544203, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/', validators=[gestion_servicios.validators.validar_tamano_archivo]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nif',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_documento',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='DNI/pasaporte u otro documento de identidad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True, help_text='Se usa para correr el plazo de HORAS_PLAZO_REGISTRO horas cuando una sustitucion se arma DESPUES de que el turno ya vencio -- ver empleados/services.py:_inicio_plazo.')),
                ('acuerdo_servicio', models.ForeignKey(blank=True, help_text='Solo para reasignacion extendida: identifica a que contrato/servicio puntual corresponde esta Ausencia. Vacio en el caso puntual de siempre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias', to='clientes.acuerdoservicio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='empleados.empleado')),
                ('sustituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustituciones', to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha real en la que comienza el turno')),
                ('hora_inicio', models.TimeField(help_text='Hora programada de inicio')),
                ('hora_fin', models.TimeField(help_text='Hora programada de fin. Si es menor o igual a hora_inicio, se asume que cruza la medianoche')),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=1, help_text='Horas realmente trabajadas. Vacio hasta que el empleado las registre', max_digits=5, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.CharField(blank=True, choices=[('ausencia_automatica', 'Ausencia'), ('autorizado', 'Autorizado')], help_text='Texto adicional que muestra el Calendario para este turno (ver empleados/services.py:detectar_ausencias_automaticas). Se limpia solo al registrar horas_reales de nuevo.', max_length=20)),
                ('confirmado_por_empleado', models.BooleanField(default=False, help_text='True si quien registro horas_reales fue el propio empleado (no un admin, ni la deteccion automatica). Una vez en True, el empleado ya no puede volver a editar horas_reales el mismo -- solo un admin, o via una SolicitudAusencia procesada.')),
                ('acuerdo_servicio', models.ForeignKey(blank=True, help_text='Acuerdo de servicio del que proviene este turno (vacio para turnos creados manualmente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='clientes.acuerdoservicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empleados.empleado')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Ultimo admin que registro/corrigio horas_reales sobre este turno. No se toca cuando quien registra es el propio empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mal_ingresada', 'Ausencia mal ingresada'), ('permiso', 'Permiso de ausencia'), ('correccion_horas', 'Corrección de horas trabajadas'), ('reasignacion_extendida', 'Reasignación extendida')], max_length=25)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Procesada')], default='pendiente', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, choices=[('aceptada', 'Aceptada tal cual'), ('rechazada', 'Rechazada'), ('corregida', 'Corregida con otro valor')], max_length=20)),
                ('nota_resolucion', models.TextField(blank=True, help_text='Nota libre del admin al procesar (ej. que se corrigio distinto de lo pedido, o por que se rechazo)')),
                ('motivo', models.TextField(blank=True)),
                ('titulo_permiso', models.CharField(blank=True, max_length=200)),
                ('descripcion_permiso', models.TextField(blank=True)),
                ('respaldo_permiso', models.FileField(blank=True, null=True, upload_to='permisos/', validators=[gestion_servicios.validators.validar_tamano_archivo])),
                ('fecha_inicio_reasignacion', models.DateField(blank=True, null=True)),
                ('fecha_fin_reasignacion', models.DateField(blank=True, null=True)),
                ('acuerdo_servicio', models.ForeignKey(blank=True, help_text='A que contrato/servicio puntual de empleado_afectado corresponde -- pasa directo a Ausencia.acuerdo_servicio si se acepta o se corrige.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_reasignacion', to='clientes.acuerdoservicio')),
                ('admin_autoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('ausencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='empleados.ausencia')),
                ('empleado_afectado', models.ForeignKey(blank=True, help_text='El empleado titular al que se le reasignan estos dias.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_propuestas', to='empleados.empleado')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ausencia', to=settings.AUTH_USER_MODEL)),
                ('sustituto_reasignacion', models.ForeignKey(blank=True, help_text='Si se indica, la ruta es sustitucion (otro empleado cubre). Vacio: ruta permiso (el titular no trabaja esos dias, con o sin paga).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_como_sustituto', to='empleados.empleado')),
                ('turno', models.ForeignKey(blank=True, help_text="Solo para tipo='correccion_horas': el turno puntual al que aplica.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_correccion', to='empleados.turno')),
            ],
        ),
    ]
