# Generated by Django 6.1.1 on 2026-09-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_ingreso'),
        ('empleados', '0002_empleado_apellido_empleado_color_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=1, max_digits=5)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('concepto', models.CharField(max_length=200)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='empleados.empleado')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='clientes.ingreso')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.servicio')),
            ],
        ),
    ]
