# Generated by Django 6.1.1 on 2026-09-15 22:09

import django.contrib.postgres.fields
import django.db.models.deletion
import encrypted_model_fields.fields
import gestion_servicios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('telefono', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('email', encrypted_model_fields.fields.EncryptedEmailField(blank=True)),
                ('direccion', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('nif', models.CharField(blank=True, help_text='NIF/identificador fiscal del cliente', max_length=50)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=21.0, help_text='Porcentaje de impuesto (IVA o similar) a aplicar a este cliente. 0 para clientes exentos.', max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(default='estandar', max_length=30)),
                ('tarifa_cliente', models.DecimalField(decimal_places=2, help_text='Importe por hora que se le cobra al cliente', max_digits=8)),
                ('compensacion_tipo', models.CharField(choices=[('por_hora', 'Por hora'), ('porcentaje_base', 'Porcentaje de lo facturado')], default='por_hora', help_text='Como se le paga al empleado por este servicio', max_length=20)),
                ('compensacion_valor', models.DecimalField(decimal_places=2, default=0, help_text="Si 'por_hora': importe por hora pagado al empleado. Si 'porcentaje_base': porcentaje (0-100) de lo facturado al cliente que recibe el empleado.", max_digits=8)),
                ('cruza_medianoche', models.BooleanField(default=False, help_text='Marcar para servicios que empiezan un dia y terminan al dia siguiente')),
                ('precio_manual', models.BooleanField(default=False, help_text='Marcar si el precio se pacta caso a caso, en vez de usar tarifa_cliente fija')),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True, help_text='Un servicio inactivo deja de estar disponible para contratos nuevos, pero los AcuerdoServicio que ya lo usan siguen intactos (proteccion PROTECT)')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('documento_pdf', models.FileField(blank=True, help_text='PDF del contrato. Se reemplaza por la version firmada cuando esta disponible', null=True, upload_to='contratos/', validators=[gestion_servicios.validators.validar_tamano_archivo])),
                ('firmas_completas', models.BooleanField(default=False, help_text='Marcar cuando se haya reemplazado el PDF por la version con las firmas')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Motivo por el que se anulo el contrato (o una parte de su periodo)')),
                ('fecha_inicio_anulacion', models.DateField(blank=True, help_text='Desde que fecha el contrato dejo de prestarse (inclusive)', null=True)),
                ('fecha_fin_anulacion', models.DateField(blank=True, help_text='Hasta que fecha el contrato dejo de prestarse (inclusive)', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AcuerdoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miércoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3), help_text='Dias de la semana en que se presta este servicio', size=7)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=1, help_text='Duracion tipica del turno, solo referencial para planificar', max_digits=5, null=True)),
                ('tarifa_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para servicios de precio manual. Se ignora si el servicio no lo requiere', max_digits=8, null=True)),
                ('fecha_inicio', models.DateField()),
                ('duracion_semanas', models.PositiveIntegerField(blank=True, help_text='Si se deja vacio, se asumen 4 semanas (el minimo)', null=True)),
                ('fecha_fin', models.DateField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos_servicio', to='empleados.empleado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='clientes.contrato')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos', to='clientes.servicio')),
            ],
        ),
    ]
