# Generated by Django 6.1.1 on 2026-09-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0002_empleado_apellido_empleado_color_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Inicio del periodo que resume este ingreso (lunes, si se genero automaticamente)')),
                ('periodo_fin', models.DateField(blank=True, help_text='Fin del periodo que resume este ingreso (domingo). Vacio en ingresos cargados a mano', null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iva_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pago_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('facturado', 'Facturado'), ('pagado', 'Pagado')], default='pendiente', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('acuerdo_servicio', models.ForeignKey(blank=True, help_text='Acuerdo de servicio del que se genero este ingreso (vacio en ingresos cargados a mano)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='clientes.acuerdoservicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
    ]
