# Generated by Django 6.1.1 on 2026-09-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_ingreso'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='finanzas.factura'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='ingreso',
            unique_together={('acuerdo_servicio', 'fecha')},
        ),
    ]
