# Generated by Django 6.1.1 on 2026-09-15 22:49

import django.db.models.deletion
import gestion_servicios.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_ingreso'),
        ('empleados', '0003_recibo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('dia_mes', models.IntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Numero real asignado por el contador. Vacio mientras la factura esta solicitada y sin responder', max_length=20, null=True, unique=True)),
                ('fecha_emision', models.DateField(blank=True, help_text='Vacio hasta que el contador emite la factura', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Vacio hasta que el contador emite la factura', null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrada', 'Cobrada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/', validators=[gestion_servicios.validators.validar_tamano_archivo])),
                ('comprobante_pago', models.FileField(blank=True, help_text='Respaldo de pago que envia el cliente', null=True, upload_to='pagos_facturas/', validators=[gestion_servicios.validators.validar_tamano_archivo])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clientes.cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/', validators=[gestion_servicios.validators.validar_tamano_archivo])),
                ('recibo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='empleados.recibo')),
            ],
        ),
        migrations.CreateModel(
            name='TareaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada')], default='pendiente', max_length=10)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('monto_enviado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalle_enviado', models.JSONField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_cobro', to='clientes.contrato')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo_inicio'],
                'unique_together': {('contrato', 'periodo_inicio')},
            },
        ),
    ]
